### ISSUE TITLE
Ran into issues with .env.local settings

### ISSUE THREAD

**Issue by tirolawz** [wpengine/headless-framework#135]
Hi @nickcernis,  
I was going through the tutorial to spin up an example headless site and ran into an issue with configuring the .env.local file. It appears that the secret variable has recently been changed to WP_HEADLESS_SECRET but when I try to run the project, it complains saying that "Error: WPE_HEADLESS_SECRET environment variable is not set.". Changing the variable name to WPE_HEADLESS_SECRET seems to fix the problem. 

To reproduce this issue, ran the following command to start the project:
`npx create-next-app -e https://github.com/wpengine/headless-framework/tree/canary --example-path examples/getting-started --use-npm`
I then changed into that directory, renamed .env.local.sample to .env.local and then updated my settings, then ran `npm run dev` to launch the project. 

Kind regards
Anton

**Comment by mindctrl** [comment]
@tirolawz we haven't published the update to npmjs.org yet, so it's installing a version of `@wpengine/headless` that still looks for the old variable. We should have that updated in the next day or so.

In the interim, you could clone this whole repo and run `npm run bootstrap` in the root folder and it will `npm link` the examples to the `packages/headless` directory instead of installing from npmjs.org.

**Comment by tirolawz** [comment]
Sounds good. Thank you 😊
