### ISSUE TITLE
Previewing drafts only works with a client-side request

### ISSUE THREAD

**Issue by trevanhetzel** [wpengine/headless-framework#146]
Support for previewing drafts [was merged in](https://github.com/wpengine/headless-framework/pull/122) and works great. But only if you have the `NEXT_PUBLIC_WORDPRESS_URL` config variable set instead of `WORDPRESS_URL`. That means I have to have the whole site make client side requests in order to have draft previewing capabilities. It would be great if draft previewing worked without having to update the config variable.

**Comment by nickcernis** [comment]
I can't reproduce this so far.

Test results with:

### Classic editor
🟢 Published post preview [works without `NEXT_PUBLIC_WORDPRESS_URL`]
🟢 Unpublished post preview [works without `NEXT_PUBLIC_WORDPRESS_URL`] 

### Gutenberg
🟢 Published post preview [works without `NEXT_PUBLIC_WORDPRESS_URL`] 
🔴 Unpublished post preview [fails to redirect to the front-end app due to a bug in Gutenberg, as noted in [Clay's PR](https://github.com/wpengine/headless-framework/pull/122#issue-567956847)]

I ran across a “page can't be found” response when testing Clay's PR ([details here](https://github.com/wpengine/headless-framework/pull/122#issuecomment-773952447)). It related to the editor being in focus when clicking the preview button. I can no longer reproduce it, but I wonder if that's what you're running into @trevanhetzel?

**Comment by wjohnsto** [comment]
@nickcernis To me it depends on how you define "works". Drafts (unpublished posts) work fine. Autosaves may appear to work, but in fact they do not. If I visit an autosave URL and have only `WORDPRESS_URL` set, I end up getting the current public version of the post. If I use `NEXT_PUBLIC_WORDPRESS_URL` I will end up with the autosave version, but it will be pulled in via a client-side gql request. Does this make sense?
