### ISSUE TITLE
Breakup Framework Packages

### ISSUE THREAD

**Issue by matt-landers** [wpengine/headless-framework#194]
In an effort to clearly delineate what dependencies are allowed at different levels of the framework (e.g. core, react, next), I propose that we break the framework into smaller npm packages that depend on each other. The foundational package (core) should not have a dependency on react or next. This part of the framework should be able to be used by any frontend framework including Vue, Angular, Svelte, etc.

The core package includes:
- Authentication and authorization
  - OAuth handlers
  - JWT Auth
  - Preview support
- Data fetching
  - Retrieve WP data based on the URL scheme
  - Fetch custom queries
  - Compose queries from fragments so that components can let the framework know the data it requires
  - Provide a mechanism for mutations
- Gutenberg block processing
- Communication between WP and the frontend
  - Shared styles
  - Configuration
  - Data changes

The react package includes:
- Hooks for data fetching (usePost, usePosts, etc.)
- Gutenberg block processing for react components
- Mechanism for registering components with the framework
  - Provide data requirements

The next package includes:
- Data cache sync on client and server (SSR)
- Support for preview mode

This list is not exhaustive of what we should do, but it includes what is in the framework today with some future enhancements that we know we need to address.

**Comment by wjohnsto** [comment]
This is a large issue, and it's good to see it all in one place. I think we need to break it out into smaller issues to allow for incremental progress to be made and tied to specific issues.

I propose three separate issues for breaking up what we currently have into separate projects/libraries in the `packages` directory. Each package will need to follow a similar project setup to `packages/headless`. The issues will be:

- `Setup packages/core`: Fix the current React dependency (`@apollo/client`) with our `packages/headless/src/[api|auth|config|utils]` directory as it is. 
- `Setup packages/react`: Move the React code from `packages/headless` into this package and refactor it to use `packages/core` rather than `packages/headless`. Remove all of the React components for now, we will pull them in as-needed when we have a good handle on what we want to provide with the React package.
- `Setup packages/next`: Move the Next code from `packages/headless` into this package and refactor it to use `packages/core` and `packages/react` instead of `packages/headless`. Remove `NextTemplateLoader`, `Pagination`, and `WPHead`. We will pull these back in when we have a better handle on how they should work.

The above issues would be highest priority, and we can break out your sub-bullets above into further issues to be prioritized after the initial batch of work above is completed.

**Comment by matt-landers** [comment]
Closing this issue in favor of the 3 smaller issues #198 #199 #200
