### ISSUE TITLE
Cleanup env vars 

### ISSUE THREAD

**Issue by moonmeister** [wpengine/headless-framework#369]
I'm hanging out helping the CX team go through Atlas training. there is a massive amount of confusion around `NEXT_PUBLIC_WORDPRESS_URL` vs `WORDPRESS_URL` While I support the code using 1 or both I think it would be beneficial to change the example .env.local.sample to only offer the `NEXT_PUBLIC_WORDPRESS_URL `.

- [ ] Do we want to change the code base to only fetch from `NEXT_PUBLIC_WORDPRESS_URL` and ignore `WORDPRESS_URL`?
- [ ] Remove `WORDPRESS_URL` from `.env.local.sample`. Also remove from docs if above is true. 
- [ ] If we keep both options in code verify having both set won't break anything.

**Comment by blakewilson** [comment]
@wjohnsto and I were just talking about this a few days ago. I completely agree, having both values adds a lot of confusion and I believe now there is no difference in the two.

I think we should only use `NEXT_PUBLIC_WORDPRESS_URL`

Additionally, I think we should have a single `.env.sample`, instead of the two `.env.local.sample`, and `.env.test.sample` files. I think this reduces confusion and also makes things a little more simple to get started.

**Comment by moonmeister** [comment]
I link eliminating the `.env.test.sample`

**Comment by blakewilson** [comment]
Awesome! Yeah I think this will be a good improvement for onboarding

**Comment by blakewilson** [comment]
Resolved in #374
